# .goreleaser.yml
version: 2

release:
  github:
    owner: fxnlabs
    name: function-node

before:
  hooks:
    - go mod tidy

builds:
  - id: fxn
    main: ./cmd/fxn
    binary: fxn
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: fxn-archive
    ids: ["fxn"]
    formats: 
      - tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

notarize:
    macos:
      -
        enabled: true
        ids:
          - fxn
        sign:
          certificate: "{{.Env.MACOS_SIGN_P12}}"
          password: "{{.Env.MACOS_SIGN_PASSWORD}}"
        notarize:
          issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
          key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
          key: "{{.Env.MACOS_NOTARY_KEY}}"
          wait: true
          timeout: 20m

homebrew_casks:
  - name: fxn
    repository:
      owner: fxnlabs
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/fxnlabs/function-node
    description: Function Node is the core software for providers.
    license: MIT
    commit_author:
      name: goreleaser
      email: bot@goreleaser.com