# See https://vektra.github.io/mockery/v2.43/features/configuration/
# for all configuration options.
packages:
  ./internal/registry:
    config:
      dir: ./mocks/registry
      outpkg: registry
    interfaces:
      Registry:
