version: '3.8'
services:
  function-node:
    build: .
    command: ["./fxn", "start"]
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./nodekey.json:/app/nodekey.json
      - ./model_backend.yaml:/app/model_backend.yaml