// Code generated by mockery v2.43.2. DO NOT EDIT.

package challengers

import (
	exec "os/exec"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Command provides a mock function with given fields: name, arg
func (_m *MockExecutor) Command(name string, arg ...string) *exec.Cmd {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func(string, ...string) *exec.Cmd); ok {
		r0 = rf(name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	return r0
}

// MockExecutor_Command_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Command'
type MockExecutor_Command_Call struct {
	*mock.Call
}

// Command is a helper method to define mock.On call
//   - name string
//   - arg ...string
func (_e *MockExecutor_Expecter) Command(name interface{}, arg ...interface{}) *MockExecutor_Command_Call {
	return &MockExecutor_Command_Call{Call: _e.mock.On("Command",
		append([]interface{}{name}, arg...)...)}
}

func (_c *MockExecutor_Command_Call) Run(run func(name string, arg ...string)) *MockExecutor_Command_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockExecutor_Command_Call) Return(_a0 *exec.Cmd) *MockExecutor_Command_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_Command_Call) RunAndReturn(run func(string, ...string) *exec.Cmd) *MockExecutor_Command_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
