name: Build container and push images

on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  build-nocuda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: |
            ghcr.io/fxnlabs/function-node
          tags: |
            type=schedule
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=sha,format=long
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-cuda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: |
            ghcr.io/fxnlabs/function-node
          tags: |
            type=schedule,suffix=-cuda
            type=ref,event=tag,suffix=-cuda
            type=ref,event=branch,suffix=-cuda
            type=ref,event=pr,suffix=-cuda
            type=sha,suffix=-cuda
            type=sha,format=long,suffix=-cuda
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          file: Dockerfile.cuda
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-binaries:
    needs: [build-nocuda, build-cuda]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0
      - name: Run GoReleaser Build
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: goreleaser-dist-${{ matrix.os }}
          path: dist

  release:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Move artifacts
        run: |
          mkdir -p dist/combined
          find dist -mindepth 2 -type f -exec mv {} dist/combined/ \;
          mv dist/combined/* dist/
      - name: Run GoReleaser Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
