# .goreleaser.yml
version: 2

release:
  github:
    owner: fxnlabs
    name: function-node

before:
  hooks:
    - go mod tidy

builds:
  - id: fxn
    main: ./cmd/fxn
    binary: fxn
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: fxn-archive
    builds:
      - fxn
    format: tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - github:
      owner: fxnlabs
      name: homebrew-tap
    folder: Formula
    name: fxn
    homepage: https://github.com/fxnlabs/function-node
    description: Function Node is the core software for providers.
    license: MIT
    commit_author:
      name: goreleaser
      email: bot@goreleaser.com